# Generated by Django 2.2.16 on 2022-06-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_cannot_be_me',
        ),
    ]
