# Generated by Django 2.2.16 on 2022-06-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220619_1849'),
        ('reviews', '0003_auto_20220619_1321'),
    ]

    operations = [
    ]
