# Generated by Django 2.2.16 on 2022-06-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220620_2009'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_cannot_be_me',
        ),
    ]
